### ISSUE TITLE
技術勉強会でやりたいネタ

### ISSUE THREAD

**Issue by nownabe** [Wondershake/tech-study#1]
勉強会としてやりたいこと

**Comment by nownabe** [comment]
[Welcome to Linux From Scratch!](http://www.linuxfromscratch.org/)

**Comment by nownabe** [comment]
アルゴリズム

**Comment by mmyoji** [comment]
Golang の package を読む

**Comment by mmyoji** [comment]
OOP

**Comment by mmyoji** [comment]
社内ハッカソン的なのやりたい

**Comment by nownabe** [comment]
開発合宿的な

**Comment by nownabe** [comment]
社内の雑な勉強会(LT会)

**Comment by mmyoji** [comment]
データベースリファクタリング輪読会

> https://builderscon.io/tokyo/2017/session/c8f36693-32aa-4bf1-816a-4966f3859926

https://www.amazon.co.jp/Refactoring-Databases-Evolutionary-paperback-Addison-Wesley-ebook/dp/B001QAP36E/ref=sr_1_1?s=english-books&ie=UTF8&qid=1502852630&sr=1-1&keywords=database+refactoring

**Comment by nownabe** [comment]
http://developer.hatenastaff.com/entry/2017/09/27/170000?amp=1

これやりたい

**Comment by nownabe** [comment]
[プログラミングコンテスト攻略のためのアルゴリズムとデータ構造 | 渡部 有隆, Ozy(協力), 秋葉 拓哉(協力) |本 | 通販 | Amazon](https://www.amazon.co.jp/dp/4839952957/)

**Comment by nownabe** [comment]
LT会のWiki Pageを作った

https://github.com/Wondershake/tech-study/wiki/Tech-Talks
