### ISSUE TITLE
機械学習勉強会の参加メンバーと日程を決める

### ISSUE THREAD

**Issue by nownabe** [Wondershake/tech-study#3]
* 毎週固定の時間で
* メンバーに関しては[統計学入門](https://github.com/Wondershake/ml-statistics-intro)の輪読をまわす必要があるので

**Comment by mmyoji** [comment]
* 業務時間内
* できれば午後

自分の希望です 😇

**Comment by mmyoji** [comment]
Google calendar 登録済み

**Comment by nownabe** [comment]
![img_5970](https://user-images.githubusercontent.com/1286807/29154786-eb83530a-7dd1-11e7-9d3d-c9805fd3f061.jpg)
